name: flutter_application
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.1
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_native_splash: ^1.2.1
  flutter_riverpod: ^0.14.0+3
  lint: ^1.6.0
  path: ^1.8.0
  path_provider: ^2.0.2
  sqflite: ^2.0.0+4
  visibility_detector: ^0.2.0
  uuid: ^3.0.4
  
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_native_splash:
  color: "#dedede"
  image: assets/logo.png
  color_dark: "#3d3d3d"
  image_dark: assets/logo.png

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/images/
    - assets/products_icons/
